version: '3.8'

services:
  app:
    build: .
    ports:
      - 4000:3000
    volumes:
      - ./:/app
    environment:
      - DB_CONNECTION=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=funk-society

  postgres:
    image: postgres:13
    ports:
      - 54320:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DATABASE=funk-society

volumes:
  postgres-data:
